"""initial schema

Revision ID: 304132447c9a
Revises: 
Create Date: 2026-09-03 16:30:00.914553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '304132447c9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DEV', 'QA', 'SUPER_ADMIN', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('error_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=True),
    sa.Column('screen_name_freetext', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('YET_TO_START', 'IN_PROGRESS', 'FIXED', 'TESTED_BY_QA', 'REOPENED', 'CLOSED', name='error_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='error_priority'), nullable=False),
    sa.Column('reported_by_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_log_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_log_id', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['error_log_id'], ['error_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('error_log_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_log_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('YET_TO_START', 'IN_PROGRESS', 'FIXED', 'TESTED_BY_QA', 'REOPENED', 'CLOSED', name='error_status'), nullable=True),
    sa.Column('new_status', sa.Enum('YET_TO_START', 'IN_PROGRESS', 'FIXED', 'TESTED_BY_QA', 'REOPENED', 'CLOSED', name='error_status'), nullable=False),
    sa.Column('changed_by_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['error_log_id'], ['error_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('error_log_status_history')
    op.drop_table('error_log_attachments')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('screens')
    # ### end Alembic commands ###
